### ISSUE TITLE
not expected way of case changing

### ISSUE THREAD

**Issue by radziksh** [wmaurer/vscode-change-case#5]
hi I have this code example 

> someObject.someAnotherConstant

with cursor at someAnotherConstant. I expect that after apply command: `extension.changeCase.constant` I will see this result:

> someObject.SOME_ANOTHER_CONSTANT

but I see this:

> SOME_OBJECT_SOME_ANOTHER_CONSTANT

is it possible change converting as in first example?
**ps:**
if someAnotherConstant is selected then converting is correct, but it's additional actions for select it.

**Comment by wmaurer** [comment]
Thanks for the report.
This behaviour is actually intentional so that one can convert from dot case to constant case. However I understand that this not really useful for the regular programmer, so I'm adding an option to turn it off (in fact it will be turned off by default).

A new version will be released in the next days.

**Comment by wmaurer** [comment]
This has been implemented and released.
